name: authenticator
description: "An authenticator app implemented to consume API written in NodeJs, express and postgres using supabase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts:
  stacked: ^3.1.0
  http: ^0.13.5
  go_router: ^6.0.9
  flutter_svg:
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  page_transition: ^2.0.9
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.12
  flutter_app_installer: ^1.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  color_dark: "#121212"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

  web: true

flutter:

  uses-material-design: true

  assets:
    - assets/

